---
- name: adding templates
  hosts: localhost
  connection: local
  gather_facts: true 
  vars:
    templatename: ''
    organization: ''
    inventory: ''
    project: ''
    playbook: ''
    credential: ''

  tasks:
  - name: Reading variables from CSV file
    read_csv:
      path: ./files/templates.csv
      fieldnames: template_name,organization,inventory,project,playbook,credential
      delimiter: ','
      key: templatename
    register: templatevars
    delegate_to: localhost

  - name: Here are my vars from the spreadsheet
    debug:
      var: templatevars

 # - debug: 
 #     msg: "{{ user.template_name }} and inventory is {{ user.inventory }}"
 #   loop: "{{ templatevars.list }}"
 #   loop_control:
 #     loop_var: user
 #   delegate_to: localhost

  - name: We're making templates!!
    tower_job_template:
      name: "{{ item.templatename }}"
      job_type: "run"
      organization: "{{ item.organization }}"
      inventory: "{{ item.inventory }}"
      project: "{{ item.project }}"
      playbook: "{{ item.playbook }}"
      credentials: "{{ item.credential }}"
      state: "present"
    #with_items: "{{ templatevars }}"
    loop: "{{ templatesvars.dict|dict2items }}"
    #loop: "{{ templatevars.dict }}"
    #loop_control:
    #  loop_var: user
