---
- name: adding templates
  hosts: localhost
  connection: local
  gather_facts: true 
  vars:
    template_name: ''
    organization: ''
    inventory: ''
    project: ''
    playbook: ''
    credential: ''

  tasks:
  - name: Reading variables from CSV file
    read_csv:
      path: ./files/templates.csv
      fieldnames: template_name,organization,inventory,project,playbook,credential
      delimiter: ','
      key: template_name
    register: template_vars
    delegate_to: localhost

  - name: Here are my vars from the spreadsheet
    debug:
      var: template_vars

  - debug: 
      msg: "{{ user.template_name }} and inventory is {{ user.inventory }}"
    loop: "{{ template_vars.list }}"
    loop_control:
      loop_var: user
    delegate_to: localhost

  - name: We're making templates!!
    tower_job_template:
      name: "{{ item.template_name }}"
      job_type: "run"
      organization: "{{ item.organization }}"
      inventory: "{{ item.inventory }}"
      project: "{{ item.project }}"
      playbook: "{{ item.playbook }}"
      credentials: "{{ item.credential }}"
      state: "present"
    #with_items: "{{ template_vars }}"
    #loop: "{{ templates_vars.dict|dict2items }}"
    loop: "{{ template_vars.list }}"
    loop_control:
      loop_var: user
